import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {ConfigProvider} from "antd";
import {AntdRegistry} from "@ant-design/nextjs-registry";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Ledger",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ConfigProvider
        theme={{
          components: {
            Button: {
              colorPrimary: "#00b96b",
              algorithm: true, // Enable algorithm
            },
            Input: {
              colorPrimary: "#eb2f96",
              algorithm: true, // Enable algorithm
            },
          },
        }}>
        <body className={inter.className}>
          <AntdRegistry>{children}</AntdRegistry>
        </body>
      </ConfigProvider>
    </html>
  );
}
